### ISSUE TITLE
Drag&Drop modifiers

### ISSUE THREAD

**Issue by AZholtkevych** [liveviewnative/liveview-client-swiftui#188]
We have to decide, would we use drag&drop modifiers in our development?
List of those:

https://developer.apple.com/documentation/swiftui/view/draggable(_:)
https://developer.apple.com/documentation/swiftui/view/dropdestination(for:action:istargeted:)
https://developer.apple.com/documentation/swiftui/view/itemprovider(_:)
https://developer.apple.com/documentation/swiftui/view/ondrag(_:)
https://developer.apple.com/documentation/swiftui/view/ondrop(of:istargeted:perform:)-f15m

**Comment by carson-katri** [comment]
There's a few different ways of doing drag & drop in SwiftUI. We may want to only implement the new `Transferable` method with `draggable` and `dropDestination`, instead of the `NSItemProvider` method.

Then there's `DragGesture`, which is more manual. Not sure how the gesture APIs would work in LVN atm.

**Comment by AZholtkevych** [comment]
To Q2 with modifiers

**Comment by AZholtkevych** [comment]
documentation is done in #235
