### ISSUE TITLE
Components To Implement

### ISSUE THREAD

**Issue by bcardarella** [liveviewnative/liveview-client-swiftui#2]
- [x] AsyncImage
- [x] Button
- [ ] Canvas (probably not necessary)
- [ ] Capsule
- [ ] Circle
- [ ] ColorPicker
- [ ] ControlGroup
- [ ] DatePicker
- [ ] DisclosureGroup
- [ ] Divider
- [ ] Ellipse
- [ ] Form
- [ ] Gauge
- [ ] Grid
- [ ] GridRow
- [ ] GroupBox
- [x] HStack
- [x] Image
- [ ] Label
- [ ] Link
- [x] List
- [ ] Menu
- [ ] MultiDatePicker
- [x] NavigationLink
- [ ] OutlineGroup
- [ ] PasteButton
- [ ] Picker
- [ ] ProgressView
- [x] Rectangle
- [x] RoundedRectangle
- [x] ScrollView
- [x] SecureField
- [ ] ShareLink
- [ ] Slider
- [x] Spacer
- [ ] Stepper
- [ ] Table
- [x] Text
- [ ] TextEditor
- [x] TextField
- [ ] Toggle
- [x] VStack
- [ ] ViewThatFits
- [x] ZStack

**Comment by karolsluszniak** [comment]
Hello! I see that this list doesn't cover all the SwiftUI components so my question is: is it based on some specific criteria like "basic immediate needs" or "everything that's planned/possible based on LiveView Native architecture"?

In particular I'm interested in following components that are not on this list:
- [TabView](https://developer.apple.com/documentation/swiftui/tabview) - looks like many if not most apps use this view in order to provide root-level navigation, it'd be an equivalent of whatever site/app menu we'd build in classic LV
- [WebView](https://developer.apple.com/documentation/webkit/wkwebview) - yeah, even if we go for native rendering we cannot deny the existence of HTML and I for one would find it extremely powerful if LVN could somehow mix in HTML rendering - maybe with some of the classic LV's perks like diffing or maybe just in "all or nothing" fashion (or is it a completely bad idea? if so why?)

If you'd prefer separate issue for each such component idea, please let me know and I'll repost.

**Comment by bcardarella** [comment]
@karolsluszniak yep, I can add these in. We do want a comprehensive list so anything missing please let me know.

**Comment by bcardarella** [comment]
As far as WebView, in the spirit of implementing everything we can do that but I'm not quite sure yet what the use case would be. I guess pointing to an external resouce?

**Comment by bcardarella** [comment]
But it does look like WebView is not part of SwiftUI, if that's the case then we would not implement WebView as part of this project. We will be only implementing the surface API of the public components in SwiftUI itself. For the other UI frameworks available to iOS development we want to provide a path forward for others (or us) to implement as a dependency package on top of this client.

**Comment by shadowfacts** [comment]
@karolsluszniak I've created a separate issue (#39) for TabView, since there are non-trivial design/implementation considerations.

**Comment by bcardarella** [comment]
Closing in favor of https://github.com/liveviewnative/liveview-client-swiftui/issues/42
