### ISSUE TITLE
ios client crashes if server disconnects

### ISSUE THREAD

**Issue by bcardarella** [liveviewnative/liveview-client-swiftui#4]
Steps to reproduce:

1. Run through Step 6 in the tutorial and get to the `Hello World` rendering in the native client.
2. Kill the phx server

The client will crash too. The client should instead go into a reconnect effort. Ideally in the future we will show a graceful error page or something if reconnects are taking too long

**Comment by shadowfacts** [comment]
Note for self: this is the continuation misuse error because callbacks on the socket stick around. Rather than setting them in withCheckedThrowingContinuation, there should be a uniform set of callbacks and then the coordinator should have a waitingForInitialConnection state that stores the continuation so it can be resumed only once when onOpen/onError is called. Subsequent invocations of those callbacks will just change the state w/o trying to resume a continuation.
