### ISSUE TITLE
Issues with Xcode 14.0

### ISSUE THREAD

**Issue by mayel** [liveviewnative/liveview-client-swiftui#50]
After updating to Xcode 14 I am getting compilation errors like the following on bits of code in PhoenixLiveViewNative that are under `if compiler(>=5.7)`:

LVNTutorialApp-bkjfahisyiztfhdjztpcsewumvjo/SourcePackages/checkouts/liveview-client-swiftui/Sources/PhoenixLiveViewNative/Utils/Alignment.swift:35:21: error build: Type 'Alignment' has no member 'leadingLastTextBaseline'

LVNTutorialApp-bkjfahisyiztfhdjztpcsewumvjo/SourcePackages/checkouts/liveview-client-swiftui/Sources/PhoenixLiveViewNative/LiveView.swift:108:13: error build: Cannot find 'NavigationStack' in scope

**Comment by shadowfacts** [comment]
Can you try cleaning/rebuilding and see if the error persists? That `leadingLastTextBaseline` and `NavigationStack` definitely exists, and I can build perfectly fine on Xcode 14.

**Comment by mayel** [comment]
Ah the issue seems to be that I was trying to run using Mac Catalyst as the target rather than an iOS simulator. Doing so worked fine with the previous version of Xcode but those two code blocks cause an issue since the upgrade (commenting them enables building again FYI, I tried adding in a `!targetEnvironment(macCatalyst)` but didn't get that working).

**Comment by shadowfacts** [comment]
Ah, Xcode 14.0 shipped without the new macOS SDK (since it's technically still in beta) and I guess using it to build for Mac Catalyst uses the old (iOS 15) SDK? I'm still not able to repro it, but I also have the Xcode 14.1 beta installed alongside 14.0, so who knows. I'm closing this, since Catalyst is not a platform we officially support right now, and this is going to resolve itself with the new Xcode version.
